<?php

/**
 * Derive docs/migration-map.json mechanically from the vendored classification.
 *
 * The migration map is the mechanical record behind the App's adoption change:
 * for every historical `Kumwe\App\...` FQCN the classification lists, either
 * the canonical `Kumwe\Extension\...` name it moves to in this package — the
 * rename the App's adoption performs on every reference — or the recorded
 * reason it cannot move yet and is retained in the App. Deriving the map from
 * the classification — never by hand — is what makes it impossible to miss a
 * public type: every classified type lands in exactly one of the two sets,
 * and the committed artifact is re-checked for that completeness by the test
 * suite on every clean clone.
 *
 * Canonical names come from the ordered prefix rules recorded inside the
 * generated document. Whether a type moves is decided from its source: a type
 * is portable exactly when its transitive `Kumwe\App\...` reference closure
 * stays inside the classified public surface (plus the manifest-layer support
 * values this package ports with it); the first types outside that surface
 * are recorded as the blockers. That analysis needs the App checkout, so this
 * tool runs at extraction time with `--app=PATH`; the committed artifact then
 * stands alone.
 *
 * Usage:
 *   php tools/generate-migration-map.php --app=/path/to/kumwe-app --commit=HASH
 *
 * @since 0.1.1
 */

declare(strict_types=1);

$app = null;
$commit = 'unknown';
foreach (array_slice($argv, 1) as $argument) {
    if (str_starts_with($argument, '--app=')) {
        $app = rtrim(substr($argument, strlen('--app=')), '/');
        continue;
    }
    if (str_starts_with($argument, '--commit=')) {
        $commit = substr($argument, strlen('--commit='));
        continue;
    }
    fwrite(STDERR, "Unknown argument {$argument}.\n");
    exit(1);
}
if ($app === null || !is_dir($app . '/src')) {
    fwrite(STDERR, "Pass --app=PATH pointing at a Kumwe App checkout (src/ must exist).\n");
    exit(1);
}

/**
 * Ordered prefix rewrite rules mapping App FQCNs onto canonical SDK names.
 *
 * @var list<array{from: string, to: string}> $rules
 */
$rules = [
    ['from' => 'Kumwe\\App\\Extension\\Development\\', 'to' => 'Kumwe\\Extension\\Toolchain\\'],
    ['from' => 'Kumwe\\App\\Extension\\Domain\\', 'to' => 'Kumwe\\Extension\\Manifest\\'],
    ['from' => 'Kumwe\\App\\Extension\\Application\\Package\\', 'to' => 'Kumwe\\Extension\\Package\\'],
    ['from' => 'Kumwe\\App\\Extension\\', 'to' => 'Kumwe\\Extension\\Spi\\'],
    ['from' => 'Kumwe\\App\\', 'to' => 'Kumwe\\Extension\\Spi\\'],
];

/**
 * App types this package ports as manifest-layer support values rather than moved public API.
 *
 * They are not classified, receive no moved record, and therefore never block a classified type
 * that reaches them: the SDK carries a byte-equivalent port.
 *
 * @var list<string> $support
 */
$support = [
    'Kumwe\\App\\Extension\\Domain\\ExtensionIdentifier',
];

$classificationPath = dirname(__DIR__) . '/resources/contract/classification.json';
$classification = json_decode((string) file_get_contents($classificationPath), true);
if (!is_array($classification) || !is_array($classification['types'] ?? null)) {
    fwrite(STDERR, "The vendored classification could not be read.\n");
    exit(1);
}

$public = [];
foreach ($classification['types'] as $entry) {
    if (is_array($entry) && is_string($entry['type'] ?? null)) {
        $public[$entry['type']] = true;
    }
}

$moved = [];
$retained = [];
foreach (array_keys($public) as $type) {
    $blockers = blockers($app, $type, $public, $support);
    if ($blockers === []) {
        $moved[$type] = canonicalName($type, $rules);
        continue;
    }
    sort($blockers, SORT_STRING);
    $retained[] = [
        'type' => $type,
        'blocked_by' => $blockers,
        'reason' => 'Its Kumwe\\App reference closure reaches types the classification does not list as '
            . 'public, so moving it would drag internal App surface into the SDK.',
    ];
}
ksort($moved, SORT_STRING);
usort($retained, static fn (array $left, array $right): int => strcmp($left['type'], $right['type']));

$document = [
    'format' => 'kumwe-extension-sdk-migration-map-v1',
    'note' => 'Generated by tools/generate-migration-map.php from resources/contract/classification.json; '
        . 'never hand-edited. `moved` records, for each historical Kumwe\\App FQCN, its canonical '
        . 'Kumwe\\Extension name — the rename the App\'s adoption change performs on every reference. '
        . '`retained` records every classified public type that stays in the App for now, with the '
        . 'closure members that block it; those types move with the roadmap phase that makes them '
        . 'portable. Every classified type appears in exactly one of the two sets.',
    'source' => ['repository' => 'kumwe/app', 'commit' => $commit],
    'rules' => $rules,
    'support_types' => $support,
    'moved' => $moved,
    'retained' => $retained,
];
$target = dirname(__DIR__) . '/docs/migration-map.json';
file_put_contents($target, json_encode($document, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
fwrite(STDOUT, sprintf(
    "Migration map generated: %d moved, %d retained, %d classified types covered.\n",
    count($moved),
    count($retained),
    count($moved) + count($retained),
));
exit(0);

/**
 * Map one App FQCN to its canonical SDK name through the ordered prefix rules.
 *
 * @param   string                                 $type   Classified App FQCN.
 * @param   list<array{from: string, to: string}>  $rules  Ordered prefix rules, longest first.
 *
 * @return  string  Canonical `Kumwe\Extension\...` name.
 *
 * @since   0.1.0
 */
function canonicalName(string $type, array $rules): string
{
    foreach ($rules as $rule) {
        if (str_starts_with($type, $rule['from'])) {
            return $rule['to'] . substr($type, strlen($rule['from']));
        }
    }

    return $type;
}

/**
 * Collect the non-public types one classified type transitively reaches inside `Kumwe\App`.
 *
 * The walk recurses through classified members only; the first unclassified type on any path is
 * recorded as a blocker and not entered, so the result names the boundary rather than the whole
 * internal subtree behind it.
 *
 * @param   string               $app      App checkout root.
 * @param   string               $type     Classified App FQCN to analyse.
 * @param   array<string, true>  $public   Classified public FQCN set.
 * @param   list<string>         $support  App FQCNs ported as SDK support values, never blockers.
 *
 * @return  list<string>  Sorted unclassified blockers; empty when the type is portable.
 *
 * @since   0.1.0
 */
function blockers(string $app, string $type, array $public, array $support): array
{
    $seen = [];
    $queue = [$type];
    $blockers = [];
    while ($queue !== []) {
        $current = array_pop($queue);
        if (isset($seen[$current])) {
            continue;
        }
        $seen[$current] = true;
        foreach (references($app, $current) as $reference) {
            if (in_array($reference, $support, true)) {
                continue;
            }
            if (isset($public[$reference])) {
                $queue[] = $reference;
                continue;
            }
            $blockers[$reference] = true;
        }
    }

    return array_keys($blockers);
}

/**
 * Read the `Kumwe\App` types one source file references, imports and same-namespace uses included.
 *
 * @param   string  $app   App checkout root.
 * @param   string  $type  App FQCN whose source is scanned.
 *
 * @return  list<string>  Referenced App FQCNs that resolve to a source file.
 *
 * @since   0.1.0
 */
function references(string $app, string $type): array
{
    static $cache = [];
    if (isset($cache[$type])) {
        return $cache[$type];
    }
    $path = $app . '/src/' . str_replace('\\', '/', substr($type, strlen('Kumwe\\App\\'))) . '.php';
    if (!is_file($path)) {
        return $cache[$type] = [];
    }
    $source = (string) file_get_contents($path);
    $found = [];
    preg_match_all('/^use\s+(Kumwe\\\\App\\\\[A-Za-z0-9_\\\\]+?)(?:\s+as\s+\w+)?;/m', $source, $uses);
    foreach ($uses[1] as $reference) {
        $found[$reference] = true;
    }
    preg_match_all('/namespace\s+([A-Za-z0-9_\\\\]+);/', $source, $namespaces);
    $namespace = $namespaces[1][0] ?? '';
    $imported = [];
    foreach (array_keys($found) as $reference) {
        $imported[substr($reference, (int) strrpos($reference, '\\') + 1)] = true;
    }
    $barewords = [];
    preg_match_all('/\b(?:new\s+|instanceof\s+)([A-Z][A-Za-z0-9_]*)\b/', $source, $matches);
    foreach ($matches[1] as $word) {
        $barewords[$word] = true;
    }
    preg_match_all('/\b([A-Z][A-Za-z0-9_]*)::/', $source, $matches);
    foreach ($matches[1] as $word) {
        $barewords[$word] = true;
    }
    preg_match_all('/[:,(]\s*\??([A-Z][A-Za-z0-9_]*)\s+\$/', $source, $matches);
    foreach ($matches[1] as $word) {
        $barewords[$word] = true;
    }
    preg_match_all('/\)\s*:\s*\??([A-Z][A-Za-z0-9_]*)/', $source, $matches);
    foreach ($matches[1] as $word) {
        $barewords[$word] = true;
    }
    preg_match_all('/\b(?:extends|implements)\s+([A-Z][A-Za-z0-9_,\s\\\\]*)/', $source, $matches);
    foreach ($matches[1] as $list) {
        foreach (preg_split('/[,\s]+/', $list) ?: [] as $word) {
            $word = trim($word, '\\');
            if ($word !== '' && ctype_upper($word[0]) && !str_contains($word, '\\')) {
                $barewords[$word] = true;
            }
        }
    }
    foreach (array_keys($barewords) as $word) {
        if (isset($imported[$word]) || $namespace === '') {
            continue;
        }
        $candidate = $namespace . '\\' . $word;
        if (
            str_starts_with($candidate, 'Kumwe\\App\\')
            && is_file($app . '/src/' . str_replace('\\', '/', substr($candidate, strlen('Kumwe\\App\\'))) . '.php')
        ) {
            $found[$candidate] = true;
        }
    }

    $references = [];
    foreach (array_keys($found) as $reference) {
        if (is_file($app . '/src/' . str_replace('\\', '/', substr($reference, strlen('Kumwe\\App\\'))) . '.php')) {
            $references[] = $reference;
        }
    }
    sort($references, SORT_STRING);

    return $cache[$type] = $references;
}
